[build]
  command = "npm run build"  # Build your project with npm
  publish = "build"          # Output directory for React

[build.environment]
  NODE_VERSION = "18"        # Node version to use for building the project
